# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 633)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.center = QtWidgets.QVBoxLayout()
        self.center.setObjectName("center")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.center.addItem(spacerItem1)
        self.topcenter = QtWidgets.QHBoxLayout()
        self.topcenter.setObjectName("topcenter")
        self.lefttopcenter = QtWidgets.QHBoxLayout()
        self.lefttopcenter.setObjectName("lefttopcenter")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lefttopcenter.addItem(spacerItem2)
        self.viewWidtthLabel = QtWidgets.QLabel(self.centralwidget)
        self.viewWidtthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.viewWidtthLabel.setObjectName("viewWidtthLabel")
        self.lefttopcenter.addWidget(self.viewWidtthLabel)
        self.viewWidthTextbox = QtWidgets.QLineEdit(self.centralwidget)
        self.viewWidthTextbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.viewWidthTextbox.setAlignment(QtCore.Qt.AlignCenter)
        self.viewWidthTextbox.setObjectName("viewWidthTextbox")
        self.lefttopcenter.addWidget(self.viewWidthTextbox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lefttopcenter.addItem(spacerItem3)
        self.topcenter.addLayout(self.lefttopcenter)
        self.righttopcenter = QtWidgets.QHBoxLayout()
        self.righttopcenter.setObjectName("righttopcenter")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.righttopcenter.addItem(spacerItem4)
        self.viewHeightLabel = QtWidgets.QLabel(self.centralwidget)
        self.viewHeightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.viewHeightLabel.setObjectName("viewHeightLabel")
        self.righttopcenter.addWidget(self.viewHeightLabel)
        self.viewHeightTextbox = QtWidgets.QLineEdit(self.centralwidget)
        self.viewHeightTextbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.viewHeightTextbox.setAlignment(QtCore.Qt.AlignCenter)
        self.viewHeightTextbox.setObjectName("viewHeightTextbox")
        self.righttopcenter.addWidget(self.viewHeightTextbox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.righttopcenter.addItem(spacerItem5)
        self.topcenter.addLayout(self.righttopcenter)
        self.center.addLayout(self.topcenter)
        self.keymodeTabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keymodeTabs.sizePolicy().hasHeightForWidth())
        self.keymodeTabs.setSizePolicy(sizePolicy)
        self.keymodeTabs.setMinimumSize(QtCore.QSize(530, 550))
        self.keymodeTabs.setTabPosition(QtWidgets.QTabWidget.South)
        self.keymodeTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.keymodeTabs.setElideMode(QtCore.Qt.ElideNone)
        self.keymodeTabs.setUsesScrollButtons(True)
        self.keymodeTabs.setTabsClosable(True)
        self.keymodeTabs.setMovable(True)
        self.keymodeTabs.setTabBarAutoHide(False)
        self.keymodeTabs.setObjectName("keymodeTabs")
        self.fourKTab = QtWidgets.QWidget()
        self.fourKTab.setObjectName("fourKTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fourKTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keymodeTabs.addTab(self.fourKTab, "")
        self.sevenKoneSTab = QtWidgets.QWidget()
        self.sevenKoneSTab.setObjectName("sevenKoneSTab")
        self.keymodeTabs.addTab(self.sevenKoneSTab, "")
        self.center.addWidget(self.keymodeTabs)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.center.addItem(spacerItem6)
        self.gridLayout.addLayout(self.center, 0, 2, 1, 1)
        self.right = QtWidgets.QVBoxLayout()
        self.right.setObjectName("right")
        self.topright = QtWidgets.QVBoxLayout()
        self.topright.setObjectName("topright")
        self.objectTreeLabel = QtWidgets.QLabel(self.centralwidget)
        self.objectTreeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.objectTreeLabel.setObjectName("objectTreeLabel")
        self.topright.addWidget(self.objectTreeLabel)
        self.right.addLayout(self.topright)
        self.bottomright = QtWidgets.QVBoxLayout()
        self.bottomright.setObjectName("bottomright")
        self.toolBoxLabel = QtWidgets.QLabel(self.centralwidget)
        self.toolBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toolBoxLabel.setObjectName("toolBoxLabel")
        self.bottomright.addWidget(self.toolBoxLabel)
        self.right.addLayout(self.bottomright)
        self.gridLayout.addLayout(self.right, 0, 4, 1, 1)
        self.left = QtWidgets.QVBoxLayout()
        self.left.setObjectName("left")
        self.topleft = QtWidgets.QVBoxLayout()
        self.topleft.setObjectName("topleft")
        self.propertiesLabel = QtWidgets.QLabel(self.centralwidget)
        self.propertiesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.propertiesLabel.setObjectName("propertiesLabel")
        self.topleft.addWidget(self.propertiesLabel)
        self.left.addLayout(self.topleft)
        self.bottomleft = QtWidgets.QVBoxLayout()
        self.bottomleft.setObjectName("bottomleft")
        self.resourcesLabel = QtWidgets.QLabel(self.centralwidget)
        self.resourcesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resourcesLabel.setObjectName("resourcesLabel")
        self.bottomleft.addWidget(self.resourcesLabel)
        self.left.addLayout(self.bottomleft)
        self.gridLayout.addLayout(self.left, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuKeymode = QtWidgets.QMenu(self.menubar)
        self.menuKeymode.setObjectName("menuKeymode")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setObjectName("actionImage")
        self.actionFont = QtWidgets.QAction(MainWindow)
        self.actionFont.setObjectName("actionFont")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.actionProject_Settings = QtWidgets.QAction(MainWindow)
        self.actionProject_Settings.setObjectName("actionProject_Settings")
        self.actionProject_Validate = QtWidgets.QAction(MainWindow)
        self.actionProject_Validate.setObjectName("actionProject_Validate")
        self.actionKeymode_Settings = QtWidgets.QAction(MainWindow)
        self.actionKeymode_Settings.setObjectName("actionKeymode_Settings")
        self.actionKeymode_Validate = QtWidgets.QAction(MainWindow)
        self.actionKeymode_Validate.setObjectName("actionKeymode_Validate")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.actionBeginner_Guide = QtWidgets.QAction(MainWindow)
        self.actionBeginner_Guide.setObjectName("actionBeginner_Guide")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionOpen)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuImport.addAction(self.actionImage)
        self.menuImport.addAction(self.actionFont)
        self.menuImport.addAction(self.actionFolder)
        self.menuProject.addAction(self.actionProject_Settings)
        self.menuProject.addAction(self.actionProject_Validate)
        self.menuKeymode.addAction(self.actionKeymode_Settings)
        self.menuKeymode.addAction(self.actionKeymode_Validate)
        self.menuHelp.addAction(self.actionBeginner_Guide)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuKeymode.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.keymodeTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SoundsphereSkinningTool"))
        self.viewWidtthLabel.setText(_translate("MainWindow", "width"))
        self.viewWidthTextbox.setText(_translate("MainWindow", "500"))
        self.viewHeightLabel.setText(_translate("MainWindow", "height"))
        self.viewHeightTextbox.setText(_translate("MainWindow", "500"))
        self.keymodeTabs.setTabText(self.keymodeTabs.indexOf(self.fourKTab), _translate("MainWindow", "4K"))
        self.keymodeTabs.setTabText(self.keymodeTabs.indexOf(self.sevenKoneSTab), _translate("MainWindow", "7K1S"))
        self.objectTreeLabel.setText(_translate("MainWindow", "Object Tree"))
        self.toolBoxLabel.setText(_translate("MainWindow", "Tool Box"))
        self.propertiesLabel.setText(_translate("MainWindow", "Properties"))
        self.resourcesLabel.setText(_translate("MainWindow", "Resources"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuKeymode.setTitle(_translate("MainWindow", "Keymode"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.action.setText(_translate("MainWindow", "."))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.action_2.setText(_translate("MainWindow", "."))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionFont.setText(_translate("MainWindow", "Font"))
        self.actionFolder.setText(_translate("MainWindow", "Folder"))
        self.action_3.setText(_translate("MainWindow", "."))
        self.actionProject_Settings.setText(_translate("MainWindow", "Settings"))
        self.actionProject_Validate.setText(_translate("MainWindow", "Validate"))
        self.actionKeymode_Settings.setText(_translate("MainWindow", "Settings"))
        self.actionKeymode_Validate.setText(_translate("MainWindow", "Validate"))
        self.action_4.setText(_translate("MainWindow", "."))
        self.action_5.setText(_translate("MainWindow", "."))
        self.actionBeginner_Guide.setText(_translate("MainWindow", "Beginner Guide"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action_6.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
